version: '2.2'

services:
  web:
    build: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/backend/web/staticfiles
        - media_volume:/home/backend/web/mediafiles
    expose:
        - 8000  
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
        - static_volume:/home/backend/web/staticfiles
        - media_volume:/home/backend/web/mediafiles
    ports:
        - 1337:80
    depends_on:
        - web

volumes:
  static_volume:   
  media_volume:
   
        